import type { Metadata } from "next";
import loadFont from "next/font/local";
import "./globals.css";

// Fetch Fonts
const neometricFont = loadFont({
  src: [
    {
      path: "../../public/fonts/neometric/neometric-hairline.woff",
      weight: "100",
      style: "hairline",
    },
    {
      path: "../../public/fonts/neometric/neometric-extra-light.woff",
      weight: "200",
      style: "extra-light",
    },
    {
      path: "../../public/fonts/neometric/neometric-light.woff",
      weight: "300",
      style: "light",
    },
    {
      path: "../../public/fonts/neometric/neometric-regular.woff",
      weight: "400",
      style: "regular",
    },
    {
      path: "../../public/fonts/neometric/neometric-medium.woff",
      weight: "500",
      style: "medium",
    },
    {
      path: "../../public/fonts/neometric/neometric-bold.woff",
      weight: "600",
      style: "bold",
    },
    {
      path: "../../public/fonts/neometric/neometric-extra-bold.woff",
      weight: "700",
      style: "extra-bold",
    },
    {
      path: "../../public/fonts/neometric/neometric-black.woff",
      weight: "800",
      style: "black",
    },
    {
      path: "../../public/fonts/neometric/neometric-heavy.woff",
      weight: "900",
      style: "heavy",
    },
  ],
  variable: "--font-neometric",
  display: "swap",
});

const gtWalsheim = loadFont({
  src: [
    // Thin (100)
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Thin-Trial-BF651b7fc728c4c.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Thin-Oblique-Trial-BF651b7fc66311a.otf",
      weight: "100",
      style: "italic",
    },
    // Ultra Light (200)
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Ultra-Light-Trial-BF651b7fc72b236.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Ultra-Light-Oblique-Trial-BF651b7fc635c6e.otf",
      weight: "200",
      style: "italic",
    },
    // Light (300)
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Light-Trial-BF651b7fc714941.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Light-Oblique-Trial-BF651b7fc6b04a3.otf",
      weight: "300",
      style: "italic",
    },
    // Regular (400)
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Regular-Trial-BF651b7fc71a47d.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Regular-Oblique-Trial-BF651b7fc67342f.otf",
      weight: "400",
      style: "italic",
    },
    // Medium (500)
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Medium-Trial-BF651b7fc728fb3.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Medium-Oblique-Trial-BF651b7fc69eff5.otf",
      weight: "500",
      style: "italic",
    },
    // Bold (700)
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Bold-Trial-BF651b7fc737c57.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Bold-Oblique-Trial-BF651b7fc5f06a0.otf",
      weight: "700",
      style: "italic",
    },
    // Ultra Bold (800)
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Ultra-Bold-Trial-BF651b7fc6c21e5.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Ultra-Bold-Oblique-Trial-BF651b7fc60ad12.otf",
      weight: "800",
      style: "italic",
    },
    // Black (900)
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Black-Trial-BF651b7fc736a5b.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../../public/fonts/gt-walsheim/GT-Walsheim-Black-Oblique-Trial-BF651b7fc5608e6.otf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-gt-walsheim",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${neometricFont.variable} ${gtWalsheim.variable}`}
    >
      <body className="antialiased font-sans">{children}</body>
    </html>
  );
}
